name: deploy-container

on:
  push:
    branches:
      - master
    paths:
      - "packages/container/**"
  workflow_dispatch: # Manual trigger option

defaults:
  run:
    working-directory: packages/container

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
